export enum RoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  MATCH_MANAGER = 'MATCH_MANAGER',
  CONTEST_MANAGER = 'CONTEST_MANAGER',
  USER = 'USER',
  KYC_OFFICER = 'KYC_OFFICER',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  SUPPORT_AGENT = 'SUPPORT_AGENT'
}
